services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # GRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT_ALLOW_RECOVERY=true

  mcp-ragdocs:
    build: .
    restart: always
    ports:
      - "3030:3030"  # Web interface
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDING_PROVIDER=ollama
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    depends_on:
      - qdrant
    volumes:
      - ./queue.txt:/app/queue.txt  # Persist queue file

volumes:
  qdrant_storage: